sbatch comandos_0.sh
sbatch comandos_1.sh
sbatch comandos_2.sh
sbatch comandos_3.sh
sbatch comandos_4.sh
sbatch comandos_5.sh
sbatch comandos_6.sh
sbatch comandos_7.sh
sbatch comandos_8.sh
sbatch comandos_9.sh
sbatch comandos_10.sh
sbatch comandos_11.sh
sbatch comandos_12.sh
sbatch comandos_13.sh
sbatch comandos_14.sh
sbatch comandos_15.sh
sbatch comandos_16.sh
sbatch comandos_17.sh
sbatch comandos_18.sh
sbatch comandos_19.sh
sbatch comandos_20.sh
sbatch comandos_21.sh
sbatch comandos_22.sh
sbatch comandos_23.sh
sbatch comandos_24.sh
sbatch comandos_25.sh
sbatch comandos_26.sh
sbatch comandos_27.sh
sbatch comandos_28.sh
sbatch comandos_29.sh
sbatch comandos_30.sh
sbatch comandos_31.sh
sbatch comandos_32.sh
sbatch comandos_33.sh
sbatch comandos_34.sh
sbatch comandos_35.sh
sbatch comandos_36.sh
sbatch comandos_37.sh
sbatch comandos_38.sh
sbatch comandos_39.sh
sbatch comandos_40.sh
sbatch comandos_41.sh
sbatch comandos_42.sh
sbatch comandos_43.sh
sbatch comandos_44.sh
sbatch comandos_45.sh
sbatch comandos_46.sh
sbatch comandos_47.sh
sbatch comandos_48.sh
sbatch comandos_49.sh
sbatch comandos_50.sh
sbatch comandos_51.sh
sbatch comandos_52.sh
sbatch comandos_53.sh
sbatch comandos_54.sh
sbatch comandos_55.sh
sbatch comandos_56.sh
sbatch comandos_57.sh
sbatch comandos_58.sh
sbatch comandos_59.sh
