sbatch ./codigo_2/comandos.sh
sbatch ./codigo_2/comandos_R2.sh
sbatch ./codigo_2/comandos_R8.sh
sbatch ./codigo_2/comandos_R1.sh
sbatch ./codigo_2/comandos_R4.sh
sbatch ./codigo_2/comandos_R66.sh
sbatch ./codigo_2/comandos_R70.sh
sbatch ./codigo_2/comandos_R69.sh
sbatch ./codigo_2/comandos_R91.sh
sbatch ./codigo_2/comandos_R94.sh
sbatch ./codigo_2/comandos_R63.sh
sbatch ./codigo_2/comandos_R90.sh
sbatch ./codigo_2/comandos_R64.sh
sbatch ./codigo_2/comandos_R62.sh
sbatch ./codigo_2/comandos_R51.sh
sbatch ./codigo_2/comandos_R45.sh
sbatch ./codigo_2/comandos_R11.sh
sbatch ./codigo_2/comandos_R35.sh
sbatch ./codigo_2/comandos_R28.sh
sbatch ./codigo_2/comandos_R42.sh
sbatch ./codigo_2/comandos_R15.sh
sbatch ./codigo_2/comandos_R48.sh
sbatch ./codigo_2/comandos_R25.sh
sbatch ./codigo_2/comandos_R31.sh
sbatch ./codigo_2/comandos_R24.sh
sbatch ./codigo_2/comandos_R46.sh
sbatch ./codigo_2/comandos_R38.sh
sbatch ./codigo_2/comandos_R36.sh
sbatch ./codigo_2/comandos_R33.sh
sbatch ./codigo_2/comandos_R18.sh
sbatch ./codigo_2/comandos_R22.sh
sbatch ./codigo_2/comandos_R49.sh
sbatch ./codigo_2/comandos_R27.sh
sbatch ./codigo_2/comandos_R100.sh
sbatch ./codigo_2/SC_50ns_75chol.txt
